### ISSUE TITLE
Will there be a Windows build?

### ISSUE THREAD

**Issue by whimian** [conda-forge/detectron2-feedstock#10]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by oblute** [comment]
@whimian `detectron2` has a dependency `pycocotools` which does not work on windows (https://github.com/conda-forge/pycocotools-feedstock/blob/master/recipe/meta.yaml); additionally, the original package does not support windows officially (https://github.com/facebookresearch/detectron2/issues/9), although some patching could maybe make it work. 

But the first step would be to PR `pycocotools`.

**Comment by whimian** [comment]
Thanks for the reply. @oblute
